agent:
  data_files:
    traning_history: ${PWD}/data/agent_history.csv
    weights: ${PWD}/data/weights.dat

databases:
  mock:
    package: db_env.mock

  tpch:
    package: db_env.tpch
    dbgen_directory: ${PWD}/dbgen
    connection:
      user: ${MYSQL_USER}
      password: ${MYSQL_ROOT_PASSWORD}
      host: ${MYSQL_HOST}
      port: ${MYSQL_PORT}
      db_name: ${MYSQL_DB}
    details:
      scale_factor: 0.1 # Database size in GB
      stream_count: 2  # Parallel stream number in throughput test
      refresh_file_index: 1
    data_directories:
      db_data: ${PWD}/data/db_data
      db_queries: ${PWD}/data/db_queries
      db_refresh: ${PWD}/data/db_refresh
